source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0' 
pod 'FMDB'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'YAScrollSegmentControl'
pod 'Haneke', '~> 1.0'
pod 'KVNProgress'
pod 'AFNetworking', '~> 3.0'
pod 'SVProgressHUD'
target 'IpadOrder' 
